"""
app.py — Flask API for FYP Dashboard
Serves precomputed_data.json generated by analyze.py

Endpoints:
  GET /api/summary       → summary stats (cards)
  GET /api/titles        → top job titles + salary by title
  GET /api/skills        → top skills, skills by title, optimal skills
  GET /api/trends        → salary trends + skill trends over time
  GET /api/location      → remote breakdown + top countries
    GET /api/filter        → advanced job filtering via PostgreSQL
  GET /api/all           → everything in one call (used by dashboard)
"""

import json
import os
from flask import Flask, jsonify, request
from flask_cors import CORS
from dotenv import load_dotenv
from psycopg2 import pool
from psycopg2.extras import RealDictCursor

load_dotenv()

app = Flask(__name__)

# Allow your Vercel frontend domain — update this after deploying
CORS(app, origins=[
    "http://localhost:3000",       # local dev
    "https://*.vercel.app",        # any vercel preview
])

# ─────────────────────────────────────────────
# Load precomputed data once at startup
# ─────────────────────────────────────────────
DATA_PATH = os.path.join(os.path.dirname(__file__), "precomputed_data.json")

def load_data():
    if not os.path.exists(DATA_PATH):
        raise FileNotFoundError(
            f"precomputed_data.json not found at {DATA_PATH}\n"
            "Run analyze.py first to generate it."
        )
    with open(DATA_PATH, "r") as f:
        return json.load(f)

try:
    DATA = load_data()
    print(f"[OK] Loaded precomputed data")
    print(f"     Generated at: {DATA['meta']['generated_at']}")
    print(f"     Total rows: {DATA['meta']['total_rows_processed']:,}")
except FileNotFoundError as e:
    print(f"[ERROR] {e}")
    DATA = None

# PostgreSQL (Neon) configuration for /api/filter
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
DB_POOL = None


def _normalize_bool(val):
    if isinstance(val, bool):
        return val
    if val is None:
        return False
    if isinstance(val, (int, float)):
        return val == 1
    return str(val).strip().lower() in {"true", "1", "yes", "y"}


def get_db_pool():
    """Create (once) and return a PostgreSQL connection pool."""
    global DB_POOL
    if DB_POOL is not None:
        return DB_POOL

    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL is not set")

    connect_kwargs = {"dsn": DATABASE_URL}
    if "sslmode=" not in DATABASE_URL:
        # Neon typically requires SSL by default.
        connect_kwargs["sslmode"] = "require"

    DB_POOL = pool.SimpleConnectionPool(1, 10, **connect_kwargs)
    return DB_POOL


def run_db_query(query, params=None, fetch="all"):
    db_pool = get_db_pool()
    conn = db_pool.getconn()
    try:
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute(query, params or [])
            if fetch == "one":
                return cur.fetchone()
            if fetch == "all":
                return cur.fetchall()
            return None
    finally:
        db_pool.putconn(conn)


def _parse_positive_int(value, default_value):
    try:
        parsed = int(value)
        return parsed if parsed >= 0 else default_value
    except (TypeError, ValueError):
        return default_value


def data_required(fn):
    """Decorator — returns 503 if data not loaded."""
    from functools import wraps
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if DATA is None:
            return jsonify({
                "error": "Data not ready. Run analyze.py first."
            }), 503
        return fn(*args, **kwargs)
    return wrapper


# ─────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────

@app.route("/", methods=["GET"])
def index():
    if DATA is None:
        return jsonify({"status": "error", "message": "Run analyze.py first"}), 503
    return jsonify({
        "status": "ok",
        "generated_at": DATA["meta"]["generated_at"],
        "total_rows": DATA["meta"]["total_rows_processed"],
        "endpoints": [
            "/api/summary",
            "/api/titles",
            "/api/skills",
            "/api/trends",
            "/api/location",
            "/api/filter",
            "/api/all",
        ]
    })


@app.route("/api/summary", methods=["GET"])
@data_required
def get_summary():
    return jsonify(DATA["summary_stats"])


@app.route("/api/titles", methods=["GET"])
@data_required
def get_titles():
    return jsonify({
        "top_titles": DATA["top_titles"],
        "salary_by_title": DATA["salary_by_title"],
    })


@app.route("/api/skills", methods=["GET"])
@data_required
def get_skills():
    return jsonify({
        "top_skills": DATA["top_skills"],
        "skills_by_title": DATA["skills_by_title"],
        "optimal_skills": DATA["optimal_skills"],
    })


@app.route("/api/trends", methods=["GET"])
@data_required
def get_trends():
    return jsonify({
        "salary_trends": DATA["salary_trends"],
        "skill_trends": DATA["skill_trends"],
    })


@app.route("/api/location", methods=["GET"])
@data_required
def get_location():
    return jsonify({
        "remote_breakdown": DATA["remote_breakdown"],
        "top_countries": DATA["top_countries"],
    })


@app.route("/api/filter", methods=["GET"])
def get_filtered_jobs():
    """Advanced filtering endpoint backed by PostgreSQL."""
    title = (request.args.get("title") or "").strip().lower()
    country = (request.args.get("country") or "").strip().lower()
    min_salary = _parse_positive_int(request.args.get("min_salary"), 0)
    max_salary = _parse_positive_int(request.args.get("max_salary"), 0)
    remote_only = _normalize_bool(request.args.get("remote"))
    limit = min(_parse_positive_int(request.args.get("limit"), 50), 200)
    offset = _parse_positive_int(request.args.get("offset"), 0)

    if max_salary and min_salary and max_salary < min_salary:
        return jsonify({"error": "max_salary cannot be less than min_salary"}), 400

    where_clauses = []
    params = []

    if title:
        where_clauses.append("LOWER(job_title) LIKE %s")
        params.append(f"%{title}%")

    if country:
        where_clauses.append("LOWER(country) LIKE %s")
        params.append(f"%{country}%")

    if min_salary:
        where_clauses.append("avg_salary IS NOT NULL AND avg_salary >= %s")
        params.append(min_salary)

    if max_salary:
        where_clauses.append("avg_salary IS NOT NULL AND avg_salary <= %s")
        params.append(max_salary)

    if remote_only:
        where_clauses.append("remote = TRUE")

    where_sql = f"WHERE {' AND '.join(where_clauses)}" if where_clauses else ""

    count_sql = f"SELECT COUNT(*) AS total FROM job_records {where_sql}"
    page_sql = f"""
        SELECT
            job_title,
            country,
            location,
            avg_salary,
            remote,
            job_schedule_type,
            company
        FROM job_records
        {where_sql}
        ORDER BY (avg_salary IS NULL) ASC, avg_salary DESC, job_title ASC
        LIMIT %s OFFSET %s
    """

    try:
        total_row = run_db_query(count_sql, params, fetch="one")
        page_rows = run_db_query(page_sql, [*params, limit, offset], fetch="all")
    except Exception as db_error:
        return jsonify({
            "error": "Database query failed",
            "details": str(db_error),
        }), 500

    results = []
    for row in page_rows:
        results.append({
            "job_title": row.get("job_title"),
            "country": row.get("country"),
            "location": row.get("location"),
            "avg_salary": row.get("avg_salary"),
            "remote": _normalize_bool(row.get("remote")),
            "job_schedule_type": row.get("job_schedule_type"),
            "company": row.get("company"),
        })

    total = int(total_row.get("total", 0)) if total_row else 0

    return jsonify({
        "filters": {
            "title": request.args.get("title", ""),
            "country": request.args.get("country", ""),
            "min_salary": min_salary,
            "max_salary": max_salary,
            "remote": remote_only,
            "limit": limit,
            "offset": offset,
        },
        "total": total,
        "returned": len(results),
        "results": results,
    })


@app.route("/api/all", methods=["GET"])
@data_required
def get_all():
    """Single endpoint — dashboard calls this once on load."""
    return jsonify(DATA)


# ─────────────────────────────────────────────
# Run
# ─────────────────────────────────────────────
if __name__ == "__main__":
    # Keep local default aligned with frontend fallback URL.
    port = int(os.environ.get("PORT", 5000))
    debug = os.environ.get("FLASK_ENV") != "production"
    print(f"Starting Flask on port {port} (debug={debug})")
    app.run(host="0.0.0.0", port=port, debug=debug)